#Web服务器：apache | nginx，通过交互式选择获取
mediawiki_webs: apache

mediawiki_vhost_dir: /etc/httpd/vhost
mediawiki_vhost_src: vhost.conf
mediawiki_service: httpd
mediawiki_owner: apache
mediawiki_db_password: "123456"
mediawiki_name: "mediawiki"
mediawiki_title: "MediaWiki"
#下载链接需定期维护
mediawiki_download_url: "https://releases.wikimedia.org/mediawiki/1.34/mediawiki-1.34.1.tar.gz"
